version: '3'

services:

  nginx:
    build: nginx
    container_name: proxy
    depends_on:
      - db
    ports:
      - "8080:80"
    networks: 
      - dlmbg

  app:
    build: app
    container_name: app
    depends_on:
      - db
    expose:
      - "8080"
    networks: 
      - dlmbg

  db:
    image: "mysql:5.7"
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root_pwd
      - MYSQL_DATABASE=db_dummy
      - MYSQL_USER=dlmbg
      - MYSQL_PASSWORD=123456
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dlmbg

networks:
  dlmbg:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"